### ISSUE TITLE
naming convention

### ISSUE THREAD

**Issue by b-schwab** [LudwigFriedmann/OpenMaterial#1]
Hi Ludwig,

great work! 
I noticed a minor typo: 'acoustic impedance' and 'Shear velocity' do not follow the usual convention of lowercase and underscores.

BR
Benedikt

**Comment by LudwigFriedmann** [comment]
Hi Benedikt,
thanks for the hint - I'll have to fix that :)
Best regards,
Ludwig

**Comment by LudwigFriedmann** [comment]
Fixed by [commit a1860c7d1095b54fcd1e4f9e40a4b4849873a9c8](https://github.com/LudwigFriedmann/OpenMaterial/commit/a1860c7d1095b54fcd1e4f9e40a4b4849873a9c8)
