### ISSUE TITLE
index of refraction of automotive materials at 77 GHz (radar)

### ISSUE THREAD

**Issue by hschoen** [LudwigFriedmann/OpenMATERIAL#10]
Here is a list of the index of refraction (N = n + i k) of some automotive materials at 77 GHz (radar):

- Iron (as example for metal)
	- n = 1000
	- k = 1000
	- Rough extrapolation ofn Fe for 77 GHz from  https://refractiveindex.info/)
	- conductivity = 1e7 S/m
- rubber
	- n = tbd
- Glass
	- n = 2.51
	- k = 0.085 
	- from [1] using Cole-Cole model, @77 GHz
	- conductivity = 1e-3 S/m
- Plexiglass (lights, windows)
	- n = 1.60
	- k = 0.0059
	- from [1] using Cole-Cole model, @77 GHz
	- conductivity = 0 S/m
- Polypropylene (as example for plastic)
	- n = 1.48
	- k = 0.0025
	- from [1] using Cole-Cole model, @77 GHz
	- conductivity = 0 S/m
- Concrete with large gravel (as example for road surface)
	- n = 1.96
	- k = 0.077
	- from [1] using Cole-Cole model, @77 GHz
	- conductivity = 1.7e-3 S/m
- Vegetation
	- n = 2.30
	- k = 1.13
(from "Radar Backscattering Of Vegetation For The Automotive 77 GHz Band" https://ieeexplore.ieee.org/document/9466234, not verified)
- Plasterboard
	- n = 1.43
	- k = 9.4e-5
(from "Dielectric Material Characterization in the Frequency Range 68 - 92 GHz" https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=8568706)

[1] Stanislav Stefanov Zhekov, Ondrej Franek, and Gert Frølund Pedersen; Dielectric Properties of Common Building Materials for Ultrawideband Propagation Studies; Digital Object Identifier 10.1109/MAP.2019.2955680

**Comment by LudwigFriedmann** [comment]
Thanks for your input @hschoen! Concerning iron, I have my doubts the values are correct :) For a wavelength of 0.00389341 m (77 GHz), I'd rather extrapolate n=1.0 and k=1.0 from the chart at refractiveindex. I'll try to gather missing parameters in order to establish full OpenMATERIAL parameter sets for the given examples. Any further input is highly appreciated!

**Comment by hschoen** [comment]
For iron, did you refer to the data from Johnson (https://refractiveindex.info/?shelf=main&book=Fe&page=Johnson)? Note, that the unit there is µm and not m. For 77 GHz radar, the wavelength is 3893 µm. I extrapolated the data from Ordal (https://refractiveindex.info/?shelf=main&book=Fe&page=Ordal) which goes up to 250 µm and got the order of n=1000 and k=1000.

**Comment by LudwigFriedmann** [comment]
Hi @hschoen, I'd happily extend the material collection based on your proposal.

Based on your research, we should complement the IOR values for a wider wavelength spectrum.

On top, I'd assume/require the following values:

**User Preferences**

- **geometrical_optics**: _true_ for all proposed materials
- **include_diffraction**: _false_ (for now)
- **include_numerical_simulation**: _false_ for all proposed materials
- **material_scheme**: _surface_ for all proposed materials
- **material_classification**:
 --  _solid-metal_ (Iron)
 -- _solid-elastomer_ (Rubber)
 -- _solid-glass_ (Glass)
 -- _solid-acrylic-glass_ (Plexiglass)
 -- _solid-thermoplastic_ (Polypropylene)
 -- _solid-concrete_ (Concrete with large gravel) 
 -- _solid-vegetation_ (Vegetation)
 -- _solid-compound_ (Plasterboard)
 The latter is not as straightforward to implement, though, and would require further discussion.
 - **material_type**
 -- **isotropic** _true_ for all proposed materials except plasterboard
 -- **homogenous** _true_ for all proposed materials except plasterboard
 -- **magnetic** _false_ for all proposed materials except iron
 - **temperature**: _tbd_
- **surface_displacement_uri**: ""
- **surface_roughness**:
 -- **surface_height**: _tbd_
 -- **surface_correlation_length**: _tbd_
- **lambert_emission**: _tbd_
- **subsurface**
 -- **subsurface**: _false_ for all proposed materials
 -- **subsurface_thickness**: _0.0_ for all proposed materials
- **ingredients**:
 -- **material_ref**: _ingredients.gltf_
 -- **order**: _order.gltf_
- **coating_materials**:
 --**layer_thickness**: 0.0
 --**material_ref**: _coating.gltf_

The file references _ingredients.gltf_, _order.gltf_ and _coating.gltf_ are not yet implemented and serve as placeholders.
 
 **Physical Properties**
 
- **refractive_index_uri**: data/_material_ior.gltf
- **mean_free_path**: _tbd_
- **particle_density**: _tbd_
- **particle_cross_section**: _tbd_
- **emissive_coefficient_uri**: data/_material_emissivity.gltf
- **detection_wavelength_ranges**
-- _tbd_, wavelenght ranges for camera, radar, lidar, (ultrasound)
- **applicable_sensors**: _camera_, _radar_, _lidar_, (_ultrasound_)
- **effective_particle_area**: _tbd_
- **relative_permittivity**: _tbd_
- **relative_permeability**: _tbd_
- **electrical_resistivity**: _tbd_
- **acoustic_impedance**: _tbd_
- **shear_velocity**: _tbd_

Can we collect the missing data for the proposed materials?

**Comment by LudwigFriedmann** [comment]
This proposal is involving electrolytic conductivity, which is temperature related. Thus, it is subject to the changes implemented by #11.

**Comment by LudwigFriedmann** [comment]
Hi @hschoen, I created branch [issue_10_radar_materials](/LudwigFriedmann/OpenMaterial/tree/issue_10_radar_materials) for this issue.
For the global parameters, I had to most of them to 0.0 due to lack of data (see 'tbd' above). I assumed temperature to 300K.

Concerning the look-up tables, I didn't find any sources for conductivity and therefore left this info blank.

For vegetation and plasterboard, no conductivity was given. For rubber, no complex IOR nor conductivity was given.
In these cases, I wasn't able to create corresponding datasets.

Let's try to fill the gaps ;)

**Comment by LudwigFriedmann** [comment]
In further discussions, the idea of specifying radar materials via relative permittivity and permeability arose.
The two parameters are measured at constant temperature and incident angle.
During measurements, frequency may vary.

I created a seperate branch [issue_10_radar_materials_permeability_permittivity](https://github.com/LudwigFriedmann/OpenMaterial/tree/issue_10_radar_materials_permeability_permittivity) to implement this alternative approach for specifying radar materials.

**Comment by LudwigFriedmann** [comment]
Transferred to https://github.com/asam-ev/OpenMATERIAL/issues/9
