### ISSUE TITLE
Make error in pathtracer

### ISSUE THREAD

**Issue by ClemensLinnhoff** [LudwigFriedmann/OpenMaterial#34]
Using Ubuntu 22 with CMake 3.22.1 I cannot build the pathtracer example. After executing the make command, I get the following error:

`../external/doctest/doctest.h:4107:47: error: size of array ‘altStackMem’ is not an integral constant-expression`

Is there any solution to this?

**Comment by LudwigFriedmann** [comment]
Hi @ClemensLinnhoff,
This error occurs for recent  glibc versions due to the fact that SIGSTKSZ is no longer a constant. A quick workaround is to replace SIGSTKSZ in line 4107 of doctest.h by 32768. Meanwhile, I'll prepare an update of doctest (where this issue has already been fixed).

**Comment by ClemensLinnhoff** [comment]
Thank you for the quick response! The workaround works. I'll leave the issue open in case others also stumble across this error until it is fixed.
