### ISSUE TITLE
refractive index, permittivity and permeability

### ISSUE THREAD

**Issue by hschoen** [LudwigFriedmann/OpenMATERIAL#4]
I think there is a functional relationship between refractive index, permittivity and permeability. Hence they cannot be defined independently.
See https://de.wikipedia.org/wiki/Permittivit%C3%A4t (Frequenzabhängigkeit)

**Comment by LudwigFriedmann** [comment]
You're right - depending on the availability of data for specific temperature and wavelength ranges the other values can be derived. What do you think about an inline comment in the schema to point out that relationship?

**Comment by hschoen** [comment]
An inline comment is a good start. The best solution would be that the third value is automatically computed from the other two if they are available (for specific temperature and wavelength ranges). But I guess this is not supported...

**Comment by hschoen** [comment]
Some more related points:
1. Permittivity strongly depends on frequency. what is the frequency at which permittivity is given?
2. For some materials the index of refraction is given (e.g. aluminium_ior.gltf). One should either use index of refraction (with n and k) or permittivity (with e1 and e2) and not mix both as they are related to each other.
3. In general, permittivity is complex. Real and imaginary part should be given.

**Comment by LudwigFriedmann** [comment]
Since the index of refraction is more common and may be used troughout all wavelength ranges, I would rather tend to the use of this parameter and drop permittivity.

**Comment by LudwigFriedmann** [comment]
I'd like to give an update on this long-running issue:

Meanwhile, the use of the three wavelength-specific parameters (complex) refractive index, relative permeability, and relative permittivity is well established within OpenMATERIAL users. Corresponding extensions have been created within OpenMATERIAL (see https://github.com/LudwigFriedmann/OpenMATERIAL/tree/master/glTF_extensions) .

While the refractive index is rather used in simulations in the optical wavelength range, relative permeability and permittivity are used in radar simulations.

The situation is similar in the measurement of corresponding data. Use-case specific, either the refractive index or the relative permeability and relative permittivity is measured. Therefore, the three values will continue to coexist. Ultimately, it is up to the user to decide which data to prioritize or whether to convert existing data from other use-cases. 

@hschoen , if this answer is satisfactory for you, I'd close the topic.

**Comment by hschoen** [comment]
Yes, I guess this is a practical way. However, it should be noted in the parameter description (if not done yet) that there is a functional relation between refractive index and permittivity that must be taken into account.

Mit freundlichen Grüßen / Best regards

Helmut Schön
CR/AEL1

Tel. +49 711 811-10880 | Mobil +49 173 9187997
​
Von: LudwigFriedmann ***@***.***>
Gesendet: Freitag, 14. April 2023 10:44
An: LudwigFriedmann/OpenMATERIAL ***@***.***>
Cc: Schoen Helmut (CR/AEL1) ***@***.***>; Mention ***@***.***>
Betreff: Re: [LudwigFriedmann/OpenMATERIAL] refractive index, permittivity and permeability (#4)


I'd like to give an update on this long-running issue:

Meanwhile, the use of the three wavelength-specific parameters (complex) refractive index, relative permeability, and relative permittivity is well established within OpenMATERIAL users. Corresponding extensions have been created within OpenMATERIAL (see https://github.com/LudwigFriedmann/OpenMATERIAL/tree/master/glTF_extensions) .

While the refractive index is rather used in simulations in the optical wavelength range, relative permeability and permittivity are used in radar simulations.

The situation is similar in the measurement of corresponding data. Use-case specific, either the refractive index or the relative permeability and relative permittivity is measured. Therefore, the three values will continue to coexist. Ultimately, it is up to the user to decide which data to prioritize or whether to convert existing data from other use-cases.

@hschoen<https://github.com/hschoen> , if this answer is satisfactory for you, I'd close the topic.

**Comment by LudwigFriedmann** [comment]
@hschoen : Done. Added remarks to documentation and schema file by [21fd30f](https://github.com/LudwigFriedmann/OpenMATERIAL/commit/21fd30f74e216aa87d478e5f494426a117d20466)
