### ISSUE TITLE
Add retroreflective material

### ISSUE THREAD

**Issue by ClemensLinnhoff** [LudwigFriedmann/OpenMATERIAL#43]
Especially for lidar, retroreflective materials such as road signs and license plates are important.

I suggest either to include a flag if a material is retroreflective for a certain wavelength(region).
Or to be more precise, we need to introduce a "retroreflectivity" value, because no material is perfectly retroreflective. If it was, road signs would be dark for the human eye. So there is always a diffuse portion.
The problem is, I don't have a good idea how to physically set this parameter.

**Comment by LudwigFriedmann** [comment]
Specular reflection could potentially be replaced by retro reflection using a binary flag (if true, light is directly reflected to the emitter). What seems to be more complex is diffuse reflection. How could this be modelled in the case of a retro-reflector?

It seems to be unrealistic to model this effect by geometry for camera or LIDAR. For larger wavelengths (e.g. radar), the problem may be solved by geometry...

**Comment by LudwigFriedmann** [comment]
Transferred to https://github.com/asam-ev/OpenMATERIAL/issues/5
