### ISSUE TITLE
Create Blender Export Scripts for OpenMATERIAL Extension Support

### ISSUE THREAD

**Issue by LudwigFriedmann** [LudwigFriedmann/OpenMATERIAL#46]
A Blender third-party add-on featuring specification of OpenMATERIAL references would enable convenient creation of glTF files supporting both the use-case of rendering and sensor simulation

https://docs.blender.org/manual/en/latest/addons/import_export/scene_gltf2.html#third-party-gltf-extensions
https://github.com/KhronosGroup/glTF-Blender-IO/tree/main/example-addons/

**Comment by ClemensLinnhoff** [comment]
I agree, this would be extremely helpful!
Is there already work ongoing on this?

**Comment by LudwigFriedmann** [comment]
Not yet :)

**Comment by LudwigFriedmann** [comment]
Transferred to https://github.com/asam-ev/OpenMATERIAL/issues/4
