### ISSUE TITLE
Improvements on vehicle structure

### ISSUE THREAD

**Issue by MD-Engineering** [LudwigFriedmann/OpenMATERIAL#6]
This issue shall become a collection of inputs concerning improvements on the 3d vehicle structure definitoin. I will start with some ideas and provide further input along the discussion.

Proposed text (draft):

**3D Model Structure**
The structure of 3D models that may be used in simulation-based development for ADAS and automated driving shall be harmonized in a way that allows for easy interfacing by various applications.

**Vehicles**
Vehicles represent a large class of entities that may be included in a 3d representation of a virtual environment. They may be placed at any location and orientation, and they may consist of static and dynamic components. The following hierarchy shall facilitate the definition of vehicle models and their exchange among various applications.

_Basic Vehicles_
Vehicles include everything that has at least one wheel, may carry humans and/or goods and is powered by an on-board engine or pushed or designed to be dragged (ie, trailer) by another vehicle with on-board engine. A human may be considered as on-board engine if power is exerted on the vehicle (eg, bicycle).

_Combined Vehicles_
Vehicles may come as standalone objects (eg, a typical passenger car) or as combinations of objects (eg, truck or pick-up truck with semitrailer, passenger car or truck with drawbar trailer or turntable trailer, train with coaches). Therefore, it is necessary to describe potential connection points (hitch points) between vehicles, so that they may be chained together (eg, a tram consisting of multiple carriages, or the typical Australian “road train” – a truck with more than one trailer).

_Axles and Wheels_
Vehicles may come as single-track (eg, motorcycle) or multi-track (eg, passenger car), or mixed (eg, trike) entities. The number of axles shall not be limited (eg, for large flatbed trailers for extra heavy loads). Each axle may bear multiple wheels which are (potentially) steerable. An exception in terms of steering are turntable trailers (where the whole front axle turns around a center pivot point; they may be modeled by considering the turntable itself a single-axle, dual-track model with a (pseudo) semitrailer attached to the pivot point.
![Vehicle_Structure_Axles_and_Wheels](https://user-images.githubusercontent.com/76447434/122730447-82f6fd80-d27a-11eb-880d-d95a83a89213.png)

_Multiple bodies_
Vehicle may consist of a single rigid body with attached wheels or as multi-body entities. A truck with a suspended driver cabin shall be considered a dual-body vehicle.

**Comment by LudwigFriedmann** [comment]
Hi @MD-Engineering, thanks for your input!
We just added an [example for a regular car](https://github.com/LudwigFriedmann/OpenMaterial/tree/master/model_structure/objects) - examples for other vehicles will follow. I defintely see your point here and we'll adopt the specification to incorporate vehicles with more/less than 2 axles.

**Comment by LudwigFriedmann** [comment]
Transferred to https://github.com/asam-ev/OpenMATERIAL/issues/10
