### ISSUE TITLE
Concept for integration of incident-angle dependant BRDFs/BSDFs

### ISSUE THREAD

**Issue by LudwigFriedmann** [LudwigFriedmann/OpenMATERIAL#7]
A generic concept for the integration of incident-angle dependant BRDFs (Bidirectional Reflectance Distribution Functions) / BSDFs (Bidirectional Scatter Distribution Functions) shall be introduced in OpenMATERIAL.

A global transparency Boolean distinguishes BRDF and BSDF.

Relevant inputs/dimensions for look-up tables, located in specific files, are (top to bottom):

1. Temperature
2. Polarization
3. Wavelength
4. Incident Angle (Theta, Phi)

Those dimensions shall point to entries of  a 2D array of maps (dimensions: Theta/Phi scatter)
Maps shall comprise the following values:

- Scatter probability
- Phase shift

New extension OpenMaterial_brdf_bsdf_data required.

**Comment by LudwigFriedmann** [comment]
There's no current demand to support generic BRDFs/BSDFs

**Comment by ClemensLinnhoff** [comment]
I wouldn't completely rule it out. I know at least one commercial simulation tool vendor who uses measured BRDFs of different materials as look-up tables for their lidar simulation. So there might be a use-case for OpenMaterial somewhere in the future. But then this issue can be reopened.
