### ISSUE TITLE
detection_wavelength_range for ultrasound

### ISSUE THREAD

**Issue by hschoen** [LudwigFriedmann/OpenMaterial#9]
In the examples given, the detection_wavelength_ranges for typical_sensor: ultrasound is 100 to 15000. However, these values are rather audible frequencies. Ultrasound devices operate with frequencies from 20 kHz up to several GHz. Hence the detection_wavelength_range is 1.66e-2 to 1e-7 m.

**Comment by LudwigFriedmann** [comment]
While you're theroretically right, I briefly remember that air-coupled applications are limited to frequencies below 500 kHz. For liquids and solids, higher frequencies ranges are relevant. How about a range of 20 kHz - 500 kHz?

**Comment by hschoen** [comment]
The range of 20 kHz - 500 kHz sounds reasonable but my point is that the units were probably confused. The unit of detection_wavelength_range must be meter instead of Hz.

**Comment by LudwigFriedmann** [comment]
Will fix it

**Comment by LudwigFriedmann** [comment]
Fixed with https://github.com/LudwigFriedmann/OpenMaterial/commit/db9feb4e071de68bfa4e8bd9b96efcbca5131220
